// AUTO-GENERATED — do not edit by hand.
// Source: VS Code bundled Seti file-icon theme (dark variant only).
//   https://github.com/microsoft/vscode/blob/main/extensions/theme-seti/icons/vs-seti-icon-theme.json
//   font: apps/web/public/fonts/seti.woff
//   seti-ui commit: https://github.com/jesseweed/seti-ui/commit/2d6c5e68b4ded73c92dac291845ee44e1182d511
// Regenerate by re-running the generator over the upstream JSON (see git history).
//
// Each icon def is a glyph in the `seti` font (private-use codepoint) plus its
// color. VS Code resolves a file to an icon id via, in order: exact fileName →
// longest matching fileExtension suffix → languageId. The languageId step is why
// the resolver (seti-icons.ts) carries an ext/name → languageId table: common
// source extensions (ts, js, py, json, css…) live ONLY under languageIds here.

export interface SetiIconDef { c: string; color: string }

export const SETI_DEFAULT = "_default";

export const SETI_ICON_DEFS: Record<string, SetiIconDef> = {
  "_R": { c: "\uE001", color: "#519aba" },
  "_argdown": { c: "\uE003", color: "#519aba" },
  "_asm": { c: "\uE004", color: "#cc3e44" },
  "_audio": { c: "\uE005", color: "#a074c4" },
  "_babel": { c: "\uE006", color: "#cbcb41" },
  "_bazel": { c: "\uE007", color: "#8dc149" },
  "_bazel_1": { c: "\uE007", color: "#4d5a5e" },
  "_bicep": { c: "\uE008", color: "#519aba" },
  "_bower": { c: "\uE009", color: "#e37933" },
  "_bsl": { c: "\uE00A", color: "#cc3e44" },
  "_c": { c: "\uE00C", color: "#519aba" },
  "_c-sharp": { c: "\uE00B", color: "#519aba" },
  "_c_1": { c: "\uE00C", color: "#a074c4" },
  "_c_2": { c: "\uE00C", color: "#cbcb41" },
  "_cake": { c: "\uE00D", color: "#cc3e44" },
  "_cake_php": { c: "\uE00E", color: "#cc3e44" },
  "_clock": { c: "\uE012", color: "#519aba" },
  "_clock_1": { c: "\uE012", color: "#6d8086" },
  "_clojure": { c: "\uE013", color: "#8dc149" },
  "_clojure_1": { c: "\uE013", color: "#519aba" },
  "_code-climate": { c: "\uE014", color: "#8dc149" },
  "_code-search": { c: "\uE015", color: "#a074c4" },
  "_coffee": { c: "\uE016", color: "#cbcb41" },
  "_coldfusion": { c: "\uE018", color: "#519aba" },
  "_config": { c: "\uE019", color: "#6d8086" },
  "_cpp": { c: "\uE01A", color: "#519aba" },
  "_cpp_1": { c: "\uE01A", color: "#a074c4" },
  "_cpp_2": { c: "\uE01A", color: "#cbcb41" },
  "_crystal": { c: "\uE01B", color: "#d4d7d6" },
  "_crystal_embedded": { c: "\uE01C", color: "#d4d7d6" },
  "_css": { c: "\uE01D", color: "#519aba" },
  "_csv": { c: "\uE01E", color: "#8dc149" },
  "_cu": { c: "\uE01F", color: "#8dc149" },
  "_cu_1": { c: "\uE01F", color: "#a074c4" },
  "_d": { c: "\uE020", color: "#cc3e44" },
  "_dart": { c: "\uE021", color: "#519aba" },
  "_db": { c: "\uE022", color: "#f55385" },
  "_db_1": { c: "\uE022", color: "#519aba" },
  "_default": { c: "\uE023", color: "#d4d7d6" },
  "_docker": { c: "\uE025", color: "#519aba" },
  "_docker_1": { c: "\uE025", color: "#4d5a5e" },
  "_docker_2": { c: "\uE025", color: "#8dc149" },
  "_docker_3": { c: "\uE025", color: "#f55385" },
  "_ejs": { c: "\uE027", color: "#cbcb41" },
  "_elixir": { c: "\uE028", color: "#a074c4" },
  "_elixir_script": { c: "\uE029", color: "#a074c4" },
  "_elm": { c: "\uE02A", color: "#519aba" },
  "_eslint": { c: "\uE02C", color: "#a074c4" },
  "_eslint_1": { c: "\uE02C", color: "#4d5a5e" },
  "_ethereum": { c: "\uE02D", color: "#519aba" },
  "_f-sharp": { c: "\uE02E", color: "#519aba" },
  "_favicon": { c: "\uE02F", color: "#cbcb41" },
  "_firebase": { c: "\uE030", color: "#e37933" },
  "_firefox": { c: "\uE031", color: "#e37933" },
  "_font": { c: "\uE033", color: "#cc3e44" },
  "_git": { c: "\uE034", color: "#41535b" },
  "_github": { c: "\uE037", color: "#d4d7d6" },
  "_gitlab": { c: "\uE038", color: "#e37933" },
  "_go": { c: "\uE039", color: "#519aba" },
  "_go2": { c: "\uE03A", color: "#519aba" },
  "_godot": { c: "\uE03B", color: "#519aba" },
  "_godot_1": { c: "\uE03B", color: "#cc3e44" },
  "_godot_2": { c: "\uE03B", color: "#cbcb41" },
  "_godot_3": { c: "\uE03B", color: "#a074c4" },
  "_gradle": { c: "\uE03C", color: "#519aba" },
  "_grails": { c: "\uE03D", color: "#8dc149" },
  "_graphql": { c: "\uE03E", color: "#f55385" },
  "_grunt": { c: "\uE03F", color: "#e37933" },
  "_gulp": { c: "\uE040", color: "#cc3e44" },
  "_hacklang": { c: "\uE041", color: "#e37933" },
  "_haml": { c: "\uE042", color: "#cc3e44" },
  "_happenings": { c: "\uE043", color: "#519aba" },
  "_haskell": { c: "\uE044", color: "#a074c4" },
  "_haxe": { c: "\uE045", color: "#e37933" },
  "_haxe_1": { c: "\uE045", color: "#cbcb41" },
  "_haxe_2": { c: "\uE045", color: "#519aba" },
  "_haxe_3": { c: "\uE045", color: "#a074c4" },
  "_heroku": { c: "\uE046", color: "#a074c4" },
  "_hex": { c: "\uE047", color: "#cc3e44" },
  "_html": { c: "\uE048", color: "#519aba" },
  "_html_1": { c: "\uE048", color: "#8dc149" },
  "_html_2": { c: "\uE048", color: "#cbcb41" },
  "_html_3": { c: "\uE048", color: "#e37933" },
  "_html_erb": { c: "\uE049", color: "#cc3e44" },
  "_ignored": { c: "\uE04A", color: "#41535b" },
  "_illustrator": { c: "\uE04B", color: "#cbcb41" },
  "_image": { c: "\uE04C", color: "#a074c4" },
  "_info": { c: "\uE04D", color: "#519aba" },
  "_ionic": { c: "\uE04E", color: "#519aba" },
  "_jade": { c: "\uE04F", color: "#cc3e44" },
  "_java": { c: "\uE050", color: "#cc3e44" },
  "_java_1": { c: "\uE050", color: "#519aba" },
  "_javascript": { c: "\uE051", color: "#cbcb41" },
  "_javascript_1": { c: "\uE051", color: "#e37933" },
  "_javascript_2": { c: "\uE051", color: "#519aba" },
  "_jenkins": { c: "\uE052", color: "#cc3e44" },
  "_jinja": { c: "\uE053", color: "#cc3e44" },
  "_json": { c: "\uE055", color: "#cbcb41" },
  "_json_1": { c: "\uE055", color: "#8dc149" },
  "_julia": { c: "\uE056", color: "#a074c4" },
  "_karma": { c: "\uE057", color: "#8dc149" },
  "_kotlin": { c: "\uE058", color: "#e37933" },
  "_less": { c: "\uE059", color: "#519aba" },
  "_license": { c: "\uE05A", color: "#cbcb41" },
  "_license_1": { c: "\uE05A", color: "#e37933" },
  "_license_2": { c: "\uE05A", color: "#cc3e44" },
  "_liquid": { c: "\uE05B", color: "#8dc149" },
  "_livescript": { c: "\uE05C", color: "#519aba" },
  "_lock": { c: "\uE05D", color: "#8dc149" },
  "_lua": { c: "\uE05E", color: "#519aba" },
  "_makefile": { c: "\uE05F", color: "#e37933" },
  "_makefile_1": { c: "\uE05F", color: "#a074c4" },
  "_makefile_2": { c: "\uE05F", color: "#6d8086" },
  "_makefile_3": { c: "\uE05F", color: "#519aba" },
  "_markdown": { c: "\uE060", color: "#519aba" },
  "_maven": { c: "\uE061", color: "#cc3e44" },
  "_mdo": { c: "\uE062", color: "#cc3e44" },
  "_mustache": { c: "\uE063", color: "#e37933" },
  "_nim": { c: "\uE065", color: "#cbcb41" },
  "_notebook": { c: "\uE066", color: "#519aba" },
  "_npm": { c: "\uE067", color: "#41535b" },
  "_npm_1": { c: "\uE067", color: "#cc3e44" },
  "_npm_ignored": { c: "\uE068", color: "#41535b" },
  "_nunjucks": { c: "\uE069", color: "#8dc149" },
  "_ocaml": { c: "\uE06A", color: "#e37933" },
  "_odata": { c: "\uE06B", color: "#e37933" },
  "_pddl": { c: "\uE06C", color: "#a074c4" },
  "_pdf": { c: "\uE06D", color: "#cc3e44" },
  "_perl": { c: "\uE06E", color: "#519aba" },
  "_photoshop": { c: "\uE06F", color: "#519aba" },
  "_php": { c: "\uE070", color: "#a074c4" },
  "_pipeline": { c: "\uE071", color: "#e37933" },
  "_plan": { c: "\uE072", color: "#8dc149" },
  "_platformio": { c: "\uE073", color: "#e37933" },
  "_powershell": { c: "\uE074", color: "#519aba" },
  "_prisma": { c: "\uE075", color: "#519aba" },
  "_prolog": { c: "\uE077", color: "#e37933" },
  "_pug": { c: "\uE078", color: "#cc3e44" },
  "_puppet": { c: "\uE079", color: "#cbcb41" },
  "_purescript": { c: "\uE07A", color: "#d4d7d6" },
  "_python": { c: "\uE07B", color: "#519aba" },
  "_react": { c: "\uE07D", color: "#519aba" },
  "_react_1": { c: "\uE07D", color: "#e37933" },
  "_reasonml": { c: "\uE07E", color: "#cc3e44" },
  "_rescript": { c: "\uE07F", color: "#cc3e44" },
  "_rescript_1": { c: "\uE07F", color: "#f55385" },
  "_rollup": { c: "\uE080", color: "#cc3e44" },
  "_ruby": { c: "\uE081", color: "#cc3e44" },
  "_rust": { c: "\uE082", color: "#6d8086" },
  "_salesforce": { c: "\uE083", color: "#519aba" },
  "_sass": { c: "\uE084", color: "#f55385" },
  "_sbt": { c: "\uE085", color: "#519aba" },
  "_scala": { c: "\uE086", color: "#cc3e44" },
  "_shell": { c: "\uE089", color: "#8dc149" },
  "_slim": { c: "\uE08A", color: "#e37933" },
  "_smarty": { c: "\uE08B", color: "#cbcb41" },
  "_spring": { c: "\uE08C", color: "#8dc149" },
  "_stylelint": { c: "\uE08D", color: "#d4d7d6" },
  "_stylelint_1": { c: "\uE08D", color: "#4d5a5e" },
  "_stylus": { c: "\uE08E", color: "#8dc149" },
  "_sublime": { c: "\uE08F", color: "#e37933" },
  "_svelte": { c: "\uE090", color: "#cc3e44" },
  "_svg": { c: "\uE091", color: "#a074c4" },
  "_svg_1": { c: "\uE091", color: "#519aba" },
  "_swift": { c: "\uE092", color: "#e37933" },
  "_terraform": { c: "\uE093", color: "#a074c4" },
  "_tex": { c: "\uE094", color: "#519aba" },
  "_tex_1": { c: "\uE094", color: "#cbcb41" },
  "_tex_2": { c: "\uE094", color: "#e37933" },
  "_tex_3": { c: "\uE094", color: "#d4d7d6" },
  "_todo": { c: "\uE096", color: "#d4d7d6" },
  "_tsconfig": { c: "\uE097", color: "#519aba" },
  "_twig": { c: "\uE098", color: "#8dc149" },
  "_typescript": { c: "\uE099", color: "#519aba" },
  "_typescript_1": { c: "\uE099", color: "#e37933" },
  "_vala": { c: "\uE09A", color: "#6d8086" },
  "_video": { c: "\uE09B", color: "#f55385" },
  "_vite": { c: "\uE09C", color: "#cbcb41" },
  "_vue": { c: "\uE09D", color: "#8dc149" },
  "_wasm": { c: "\uE09E", color: "#a074c4" },
  "_wat": { c: "\uE09F", color: "#a074c4" },
  "_webpack": { c: "\uE0A0", color: "#519aba" },
  "_wgt": { c: "\uE0A1", color: "#519aba" },
  "_windows": { c: "\uE0A2", color: "#519aba" },
  "_word": { c: "\uE0A3", color: "#519aba" },
  "_xls": { c: "\uE0A4", color: "#8dc149" },
  "_xml": { c: "\uE0A5", color: "#e37933" },
  "_yarn": { c: "\uE0A6", color: "#519aba" },
  "_yml": { c: "\uE0A7", color: "#a074c4" },
  "_zig": { c: "\uE0A8", color: "#e37933" },
  "_zip": { c: "\uE0A9", color: "#cc3e44" },
  "_zip_1": { c: "\uE0A9", color: "#6d8086" },
};

export const SETI_FILE_NAMES: Record<string, string> = {
  "mix": "_hex",
  "karma.conf.js": "_karma",
  "karma.conf.cjs": "_karma",
  "karma.conf.mjs": "_karma",
  "karma.conf.coffee": "_karma",
  "readme.md": "_info",
  "readme.txt": "_info",
  "readme": "_info",
  "changelog.md": "_clock",
  "changelog.txt": "_clock",
  "changelog": "_clock",
  "changes.md": "_clock",
  "changes.txt": "_clock",
  "changes": "_clock",
  "version.md": "_clock",
  "version.txt": "_clock",
  "version": "_clock",
  "mvnw": "_maven",
  "pom.xml": "_maven",
  "tsconfig.json": "_tsconfig",
  "vite.config.js": "_vite",
  "vite.config.ts": "_vite",
  "vite.config.mjs": "_vite",
  "vite.config.mts": "_vite",
  "vite.config.cjs": "_vite",
  "vite.config.cts": "_vite",
  "swagger.json": "_json_1",
  "swagger.yml": "_json_1",
  "swagger.yaml": "_json_1",
  "mime.types": "_config",
  "jenkinsfile": "_jenkins",
  "babel.config.js": "_babel",
  "babel.config.json": "_babel",
  "babel.config.cjs": "_babel",
  "build": "_bazel",
  "build.bazel": "_bazel",
  "workspace": "_bazel",
  "workspace.bazel": "_bazel",
  "bower.json": "_bower",
  "docker-healthcheck": "_docker_2",
  "eslint.config.js": "_eslint",
  "firebase.json": "_firebase",
  "geckodriver": "_firefox",
  "gruntfile.js": "_grunt",
  "gruntfile.babel.js": "_grunt",
  "gruntfile.coffee": "_grunt",
  "gulpfile": "_gulp",
  "gulpfile.js": "_gulp",
  "ionic.config.json": "_ionic",
  "ionic.project": "_ionic",
  "platformio.ini": "_platformio",
  "rollup.config.js": "_rollup",
  "sass-lint.yml": "_sass",
  "stylelint.config.js": "_stylelint",
  "stylelint.config.cjs": "_stylelint",
  "stylelint.config.mjs": "_stylelint",
  "yarn.clean": "_yarn",
  "yarn.lock": "_yarn",
  "webpack.config.js": "_webpack",
  "webpack.config.cjs": "_webpack",
  "webpack.config.mjs": "_webpack",
  "webpack.config.ts": "_webpack",
  "webpack.config.build.js": "_webpack",
  "webpack.config.build.cjs": "_webpack",
  "webpack.config.build.mjs": "_webpack",
  "webpack.config.build.ts": "_webpack",
  "webpack.common.js": "_webpack",
  "webpack.common.cjs": "_webpack",
  "webpack.common.mjs": "_webpack",
  "webpack.common.ts": "_webpack",
  "webpack.dev.js": "_webpack",
  "webpack.dev.cjs": "_webpack",
  "webpack.dev.mjs": "_webpack",
  "webpack.dev.ts": "_webpack",
  "webpack.prod.js": "_webpack",
  "webpack.prod.cjs": "_webpack",
  "webpack.prod.mjs": "_webpack",
  "webpack.prod.ts": "_webpack",
  "license": "_license",
  "licence": "_license",
  "license.txt": "_license",
  "licence.txt": "_license",
  "license.md": "_license",
  "licence.md": "_license",
  "copying": "_license",
  "copying.txt": "_license",
  "copying.md": "_license",
  "compiling": "_license_1",
  "compiling.txt": "_license_1",
  "compiling.md": "_license_1",
  "contributing": "_license_2",
  "contributing.txt": "_license_2",
  "contributing.md": "_license_2",
  "qmakefile": "_makefile_1",
  "omakefile": "_makefile_2",
  "cmakelists.txt": "_makefile_3",
  "procfile": "_heroku",
  "todo": "_todo",
  "todo.txt": "_todo",
  "todo.md": "_todo",
  "npm-debug.log": "_npm_ignored",
};

export const SETI_FILE_EXTENSIONS: Record<string, string> = {
  "bsl": "_bsl",
  "mdo": "_mdo",
  "cls": "_salesforce",
  "apex": "_salesforce",
  "asm": "_asm",
  "s": "_asm",
  "bicep": "_bicep",
  "bzl": "_bazel",
  "bazel": "_bazel",
  "build": "_bazel",
  "workspace": "_bazel",
  "bazelignore": "_bazel",
  "bazelversion": "_bazel",
  "h": "_c_1",
  "aspx": "_html",
  "ascx": "_html_1",
  "asax": "_html_2",
  "master": "_html_2",
  "hh": "_cpp_1",
  "hpp": "_cpp_1",
  "hxx": "_cpp_1",
  "h++": "_cpp_1",
  "edn": "_clojure_1",
  "cfc": "_coldfusion",
  "cfm": "_coldfusion",
  "litcoffee": "_coffee",
  "config": "_config",
  "cr": "_crystal",
  "ecr": "_crystal_embedded",
  "slang": "_crystal_embedded",
  "cson": "_json",
  "css.map": "_css",
  "sss": "_css",
  "csv": "_csv",
  "xls": "_xls",
  "xlsx": "_xls",
  "cuh": "_cu_1",
  "hu": "_cu_1",
  "cake": "_cake",
  "ctp": "_cake_php",
  "d": "_d",
  "doc": "_word",
  "docx": "_word",
  "ejs": "_ejs",
  "ex": "_elixir",
  "exs": "_elixir_script",
  "elm": "_elm",
  "ico": "_favicon",
  "gitconfig": "_git",
  "gitkeep": "_git",
  "gitattributes": "_git",
  "gitmodules": "_git",
  "slide": "_go",
  "article": "_go",
  "gd": "_godot",
  "godot": "_godot_1",
  "tres": "_godot_2",
  "tscn": "_godot_3",
  "gradle": "_gradle",
  "gsp": "_grails",
  "gql": "_graphql",
  "graphql": "_graphql",
  "graphqls": "_graphql",
  "hack": "_hacklang",
  "haml": "_haml",
  "hs": "_haskell",
  "lhs": "_haskell",
  "hx": "_haxe",
  "hxs": "_haxe_1",
  "hxp": "_haxe_2",
  "hxml": "_haxe_3",
  "jade": "_jade",
  "class": "_java_1",
  "classpath": "_java",
  "js.map": "_javascript",
  "cjs.map": "_javascript",
  "mjs.map": "_javascript",
  "spec.js": "_javascript_1",
  "spec.cjs": "_javascript_1",
  "spec.mjs": "_javascript_1",
  "test.js": "_javascript_1",
  "test.cjs": "_javascript_1",
  "test.mjs": "_javascript_1",
  "es": "_javascript",
  "es5": "_javascript",
  "es7": "_javascript",
  "jinja": "_jinja",
  "jinja2": "_jinja",
  "kt": "_kotlin",
  "kts": "_kotlin",
  "liquid": "_liquid",
  "ls": "_livescript",
  "argdown": "_argdown",
  "ad": "_argdown",
  "mustache": "_mustache",
  "stache": "_mustache",
  "nim": "_nim",
  "nims": "_nim",
  "github-issues": "_github",
  "ipynb": "_notebook",
  "njk": "_nunjucks",
  "nunjucks": "_nunjucks",
  "nunjs": "_nunjucks",
  "nunj": "_nunjucks",
  "njs": "_nunjucks",
  "nj": "_nunjucks",
  "npm-debug.log": "_npm",
  "npmignore": "_npm_1",
  "npmrc": "_npm_1",
  "ml": "_ocaml",
  "mli": "_ocaml",
  "cmx": "_ocaml",
  "cmxa": "_ocaml",
  "odata": "_odata",
  "php.inc": "_php",
  "pipeline": "_pipeline",
  "pddl": "_pddl",
  "plan": "_plan",
  "happenings": "_happenings",
  "prisma": "_prisma",
  "pp": "_puppet",
  "epp": "_puppet",
  "purs": "_purescript",
  "spec.jsx": "_react_1",
  "test.jsx": "_react_1",
  "cjsx": "_react",
  "spec.tsx": "_react_1",
  "test.tsx": "_react_1",
  "re": "_reasonml",
  "res": "_rescript",
  "resi": "_rescript_1",
  "r": "_R",
  "rmd": "_R",
  "erb": "_html_erb",
  "erb.html": "_html_erb",
  "html.erb": "_html_erb",
  "sass": "_sass",
  "springbeans": "_spring",
  "slim": "_slim",
  "smarty.tpl": "_smarty",
  "tpl": "_smarty",
  "sbt": "_sbt",
  "scala": "_scala",
  "sol": "_ethereum",
  "styl": "_stylus",
  "svelte": "_svelte",
  "soql": "_db_1",
  "tf": "_terraform",
  "tf.json": "_terraform",
  "tfvars": "_terraform",
  "tfvars.json": "_terraform",
  "dtx": "_tex_2",
  "ins": "_tex_3",
  "toml": "_config",
  "twig": "_twig",
  "spec.ts": "_typescript_1",
  "test.ts": "_typescript_1",
  "vala": "_vala",
  "vapi": "_vala",
  "component": "_html_3",
  "vue": "_vue",
  "wasm": "_wasm",
  "wat": "_wat",
  "pro": "_prolog",
  "zig": "_zig",
  "jar": "_zip",
  "zip": "_zip_1",
  "wgt": "_wgt",
  "ai": "_illustrator",
  "psd": "_photoshop",
  "pdf": "_pdf",
  "eot": "_font",
  "ttf": "_font",
  "woff": "_font",
  "woff2": "_font",
  "otf": "_font",
  "avif": "_image",
  "gif": "_image",
  "jpg": "_image",
  "jpeg": "_image",
  "png": "_image",
  "pxm": "_image",
  "svg": "_svg",
  "svgx": "_image",
  "tiff": "_image",
  "webp": "_image",
  "sublime-project": "_sublime",
  "sublime-workspace": "_sublime",
  "mov": "_video",
  "ogv": "_video",
  "webm": "_video",
  "avi": "_video",
  "mpg": "_video",
  "mp4": "_video",
  "mp3": "_audio",
  "ogg": "_audio",
  "wav": "_audio",
  "flac": "_audio",
  "3ds": "_svg_1",
  "3dm": "_svg_1",
  "stl": "_svg_1",
  "obj": "_svg_1",
  "dae": "_svg_1",
  "babelrc": "_babel",
  "babelrc.js": "_babel",
  "babelrc.cjs": "_babel",
  "bazelrc": "_bazel_1",
  "bowerrc": "_bower",
  "dockerignore": "_docker_1",
  "codeclimate.yml": "_code-climate",
  "eslintrc": "_eslint",
  "eslintrc.js": "_eslint",
  "eslintrc.cjs": "_eslint",
  "eslintrc.yaml": "_eslint",
  "eslintrc.yml": "_eslint",
  "eslintrc.json": "_eslint",
  "eslintignore": "_eslint_1",
  "firebaserc": "_firebase",
  "gitlab-ci.yml": "_gitlab",
  "jshintrc": "_javascript_2",
  "jscsrc": "_javascript_2",
  "stylelintrc": "_stylelint",
  "stylelintrc.json": "_stylelint",
  "stylelintrc.yaml": "_stylelint",
  "stylelintrc.yml": "_stylelint",
  "stylelintrc.js": "_stylelint",
  "stylelintignore": "_stylelint_1",
  "direnv": "_config",
  "static": "_config",
  "slugignore": "_config",
  "tmp": "_clock_1",
  "htaccess": "_config",
  "key": "_lock",
  "cert": "_lock",
  "cer": "_lock",
  "crt": "_lock",
  "pem": "_lock",
  "ds_store": "_ignored",
};

export const SETI_LANGUAGE_IDS: Record<string, string> = {
  "bat": "_windows",
  "clojure": "_clojure",
  "coffeescript": "_coffee",
  "jsonc": "_json",
  "json": "_json",
  "c": "_c",
  "cpp": "_cpp",
  "cuda-cpp": "_cu",
  "csharp": "_c-sharp",
  "css": "_css",
  "dart": "_dart",
  "dockerfile": "_docker",
  "dotenv": "_config",
  "ignore": "_git",
  "fsharp": "_f-sharp",
  "git-commit": "_git",
  "go": "_go2",
  "groovy": "_grails",
  "handlebars": "_mustache",
  "html": "_html_3",
  "properties": "_config",
  "java": "_java",
  "javascriptreact": "_react",
  "javascript": "_javascript",
  "julia": "_julia",
  "tex": "_tex_1",
  "latex": "_tex",
  "less": "_less",
  "lua": "_lua",
  "makefile": "_makefile",
  "markdown": "_markdown",
  "objective-c": "_c_2",
  "objective-cpp": "_cpp_2",
  "perl": "_perl",
  "php": "_php",
  "powershell": "_powershell",
  "jade": "_pug",
  "python": "_python",
  "r": "_R",
  "razor": "_html",
  "ruby": "_ruby",
  "rust": "_rust",
  "scss": "_sass",
  "search-result": "_code-search",
  "shellscript": "_shell",
  "sql": "_db",
  "swift": "_swift",
  "typescript": "_typescript",
  "typescriptreact": "_react",
  "xml": "_xml",
  "dockercompose": "_docker_3",
  "yaml": "_yml",
  "argdown": "_argdown",
  "bicep": "_bicep",
  "elixir": "_elixir",
  "elm": "_elm",
  "erb": "_html_erb",
  "github-issues": "_github",
  "gradle": "_gradle",
  "godot": "_godot",
  "haml": "_haml",
  "haskell": "_haskell",
  "haxe": "_haxe",
  "jinja": "_jinja",
  "kotlin": "_kotlin",
  "mustache": "_mustache",
  "nunjucks": "_nunjucks",
  "ocaml": "_ocaml",
  "rescript": "_rescript",
  "sass": "_sass",
  "stylus": "_stylus",
  "terraform": "_terraform",
  "todo": "_todo",
  "vala": "_vala",
  "vue": "_vue",
  "jsonl": "_json",
  "postcss": "_css",
  "django-html": "_html_3",
  "blade": "_php",
  "prompt": "_markdown",
  "instructions": "_markdown",
  "chatagent": "_markdown",
  "skill": "_markdown",
};
